##服务配置
server: 
  port: 8080

##微信公众号配置
wechat:  #测试号
  appid: 
  secret: 
  
##相关域名配置
domain:
  auth: http://test.com #授权域名(用于授权回调,需要公众号配置安全域,本工程地址)
  callback: http://test.com #回调地址,用于授权成功后将openid传递给业务方
    
    
##日志配置
logging:
  level:
    com:
      yangjie: debug